# Generated by Django 3.0.7 on 2020-07-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='bike_wieght',
            new_name='bike_weight',
        ),
        migrations.AddField(
            model_name='activity',
            name='upload_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
