# Generated by Django 3.0.7 on 2020-07-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20200701_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='upload_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
