# Generated by Django 3.0.5 on 2020-04-24 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macroplan',
            name='weekFramework',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='week',
            name='days',
        ),
        migrations.AddField(
            model_name='day',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='days', to='plans.Week'),
        ),
        migrations.AddField(
            model_name='week',
            name='weeks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weeks', to='plans.Plan'),
        ),
        migrations.AddField(
            model_name='weektype',
            name='weekFramework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weeksFramework', to='plans.MacroPlan'),
        ),
        migrations.AlterField(
            model_name='week',
            name='weekType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weekTypes', to='plans.WeekType'),
        ),
    ]
