# Generated by Django 3.0.5 on 2020-04-26 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20200424_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='day',
            new_name='week',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='weeks',
            new_name='plan',
        ),
        migrations.RenameField(
            model_name='weektype',
            old_name='weekFramework',
            new_name='macroPlan',
        ),
        migrations.AddField(
            model_name='week',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
