# Generated by Django 3.0.6 on 2020-05-09 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_auto_20200426_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weektype',
            name='macroPlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weekTypes', to='plans.MacroPlan'),
        ),
    ]
