# Generated by Django 3.0.6 on 2020-05-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hrLactateThreshold',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
