# Generated by Django 3.0.6 on 2020-05-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200509_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='athleteCategory',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='hrAerobicThreshold',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='hrLactateThreshold',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='hrMax',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='hrResting',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='isAerobicallyDeficient',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='threshold_pace',
        ),
        migrations.AddField(
            model_name='profile',
            name='athleteCategory',
            field=models.IntegerField(blank=True, choices=[(1, 'Category 1'), (2, 'Category 2')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='isAerobicallyDeficient',
            field=models.BooleanField(default=True),
        ),
    ]
