# Generated by Django 3.0.7 on 2020-07-12 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200509_1838'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
